version: '1.0'
apis:
  - openapi: openapi.yaml
    wso2Artifact: openapi.api-platform.yaml
    docsFolder: docs
    testsFolder: tests
spectralRulesets:
  - name: WSO2 REST API AI Readiness Guidelines
    sourceFolder: https://github.com/Thenujan-Nagaratnam/api-platform/tree/main/api-designer/spectral-rulesets
    fileName: ai-readiness.yaml
    rulesetContentPath: rulesetContent
  - name: OWASP Top 10
    sourceFolder: https://github.com/Thenujan-Nagaratnam/api-platform/tree/main/api-designer/spectral-rulesets
    fileName: owasp_top_10.yaml
    rulesetContentPath: rulesetContent
  - name: WSO2 API Management Guidelines
    sourceFolder: https://github.com/Thenujan-Nagaratnam/api-platform/tree/main/api-designer/spectral-rulesets
    fileName: wso2_api_management_guidelines.yaml
    rulesetContentPath: rulesetContent
  - name: WSO2 REST API Design Guidelines
    sourceFolder: https://github.com/Thenujan-Nagaratnam/api-platform/tree/main/api-designer/spectral-rulesets
    fileName: wso2_rest_api_design_guidelines.yaml
    rulesetContentPath: rulesetContent
